AppESSP/Areas/ESSP/Controllers/ESSPLeaveAppController.cs
using ESSPCORE.Common;
using ESSPCORE.EF;
using ESSPCORE.ESSP;
using ESSPSERVICE.Attendance;
using ESSPSERVICE.ESSP;
using ESSPSERVICE.Generic;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace AppESSP.Areas.ESSP.Controllers
{
    public class ESSPLeaveAppController : Controller
    {
        // GET: Attendance/EmpLeaveApp
        ILeavesESSPService ESSPLeaveService;
        ILeaveApplicationService LeaveApplicationService;
        IEntityService<VAT_LeaveApplication> VATLeaveApplicationService;
        IEntityService<Shift> ShiftService;
        IEntityService<VAT_LeaveApplicationFlow> LeaveApplicationFlowService;
        IEntityService<DailyAttendance> DailyAttendanceService;
        IEntityService<PayrollPeriod> PayrollPeriodService;
        IDDService DDService;
        public List<string> ToasterMessages = new List<string>();
        public ESSPLeaveAppController(ILeaveApplicationService leaveapplicationService, IEntityService<LeaveApplication> empleaveapplicationService, IEntityService<VAT_LeaveApplication> vATESSPLeaveApplication,
            IDDService dDService, ILeavesESSPService eSSPLeaveService, IEntityService<VAT_LeaveApplication> vATLeaveApplicationService, IEntityService<DailyAttendance> dailyAttendanceService
            , IEntityService<VAT_LeaveApplicationFlow> leaveApplicationFlowService, IEntityService<PayrollPeriod> payrollPeriodService, IEntityService<Shift> shiftService)
        {
            ESSPLeaveService = eSSPLeaveService;
            DDService = dDService;
            LeaveApplicationService = leaveapplicationService;
            VATLeaveApplicationService = vATLeaveApplicationService;
            DailyAttendanceService = dailyAttendanceService;
            LeaveApplicationFlowService = leaveApplicationFlowService;
            PayrollPeriodService = payrollPeriodService;
            ShiftService = shiftService;
        }
        public ActionResult Index(string searchString, string currentFilter, int? page)
        {
            VMLoggedUser LoggedInUser = Session["LoggedInUser"] as VMLoggedUser;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            // Disable Notifications
            int notiTypeID1 = Convert.ToInt32(NTLeaveEnum.LeaveApproved);
            int notiTypeID2 = Convert.ToInt32(NTLeaveEnum.LeaveRejected);
            int notiTypeID3 = Convert.ToInt32(NTLeaveEnum.LeaveRecommend);
            int notiTypeID4 = Convert.ToInt32(NTLeaveEnum.LeaveReverttoLM);
            Expression<Func<Notification, bool>> SpecificEntries = c => (c.UserID == LoggedInUser.PUserID && c.Status == true && (c.NotificationTypeID == notiTypeID1 || c.NotificationTypeID == notiTypeID2 || c.NotificationTypeID == notiTypeID3 || c.NotificationTypeID == notiTypeID4));
            DDService.DeleteNotification(SpecificEntries);
            List<VAT_LeaveApplication> dbVAT_LeaveApplication = ESSPLeaveService.GetIndex(LoggedInUser).OrderByDescending(aa => aa.PLeaveAppID).ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                dbVAT_LeaveApplication = dbVAT_LeaveApplication.Where(aa => aa.OEmpID.Contains(searchString) || aa.EmployeeName.ToUpper().Contains(searchString.ToUpper()) || aa.PLeaveAppID.ToString().Contains(searchString) || aa.EmployeeName.ToUpper().Contains(searchString.ToUpper()) || aa.LeaveTypeName.ToString().Contains(searchString)).ToList();
            }
            int pageSize = 500;
            int pageNumber = (page ?? 1);
            return View(dbVAT_LeaveApplication.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PendingLeaveApplicationIndex(string searchString, string currentFilter, int? page)
        {
            VMLoggedUser LoggedInUser = Session["LoggedInUser"] as VMLoggedUser;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<VAT_LeaveApplication> dbVAT_LeaveApplication = ESSPLeaveService.GetPendingLeaveRequests(LoggedInUser).OrderByDescending(aa => aa.PLeaveAppID).ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                dbVAT_LeaveApplication = dbVAT_LeaveApplication.Where(aa => aa.OEmpID.Contains(searchString) || aa.EmployeeName.ToUpper().Contains(searchString.ToUpper()) || aa.PLeaveAppID.ToString().Contains(searchString) || aa.EmployeeName.ToUpper().Contains(searchString.ToUpper()) || aa.LeaveTypeName.ToString().Contains(searchString)).ToList();
            }
            int pageSize = 500;
            int pageNumber = (page ?? 1);
            return View(dbVAT_LeaveApplication.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult RecommendAll(int?[] SelectedLvAppIds)
        {
            VMLoggedUser LoggedInUser = Session["LoggedInUser"] as VMLoggedUser;
            string Message = "";
            foreach (var item in SelectedLvAppIds)
            {
                VMESSPCommon vmESSPCommon = new VMESSPCommon();
                vmESSPCommon.PID = item;
                vmESSPCommon.Comment = "";
                Message = ESSPLeaveService.RecommendLeaveApplication(vmESSPCommon, LoggedInUser, Message);

            }
            if (Message != "")
            {
                ToasterMessages.Add(Message);
                Session["ToasterMessages"] = ToasterMessages;

            }
            return RedirectToAction("PendingLeaveApplicationIndex");
        }
        public ActionResult LeaveApplicationHistoryIndex(string searchString, string currentFilter, int? page)
        {

            VMLoggedUser LoggedInUser = Session["LoggedInUser"] as VMLoggedUser;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<VAT_LeaveApplication> dbVAT_LeaveApplication = ESSPLeaveService.GetEmpLeaveHistory(LoggedInUser);
            if (!String.IsNullOrEmpty(searchString))
            {
                dbVAT_LeaveApplication = dbVAT_LeaveApplication.Where(aa => aa.OEmpID.Contains(searchString) || aa.EmployeeName.ToUpper().Contains(searchString.ToUpper()) || aa.PLeaveAppID.ToString().Contains(searchString) || aa.EmployeeName.ToUpper().Contains(searchString.ToUpper()) || aa.LeaveTypeName.ToString().Contains(searchString)).ToList();
            }
            int pageSize = 500;
            int pageNumber = (page ?? 1);
            return View(dbVAT_LeaveApplication.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            LeaveApplication obj = new LeaveApplication();
            HelperMethod(obj);
            return View(obj);
        }
        [HttpPost]
        public ActionResult Create(LeaveApplication lvapplication)
        {
            VMLoggedUser LoggedInUser = Session["LoggedInUser"] as VMLoggedUser;

            if (lvapplication.LeaveAddress == "" || lvapplication.LeaveAddress == null)
                ModelState.AddModelError("LeaveAddress", "Contact number is mandatory !");
            if (lvapplication.LeaveAddress != null)
            {
                Match match = Regex.Match(lvapplication.LeaveAddress, @"^-*[0-9,\-]+$");
                if (!match.Success)
                {
                    ModelState.AddModelError("LeaveAddress", "Enter a valid Contact No");
                }
            }

            if (lvapplication.FromDate.Date > lvapplication.ToDate.Date)
                ModelState.AddModelError("FromDate", "From Date should be smaller than To Date");
            FinancialYear dbFinancialYear = DDService.GetFinancialYear().Where(aa => aa.PFinancialYearID == lvapplication.FinancialYearID).First();
            if (lvapplication.ToDate >= dbFinancialYear.FYEndDate || lvapplication.ToDate <= dbFinancialYear.FYStartDate)
                ModelState.AddModelError("FromDate", "To Date must lie in selected financial year");
            if (lvapplication.ToDate > AppAssistant.MaxDate)
                ModelState.AddModelError("ToDate", "Date cannot be greater than " + AppAssistant.MaxDate.ToString("dd-MM-yyyy"));
            if (lvapplication.FromDate < AppAssistant.MinDate)
                ModelState.AddModelError("FromDate", "Date cannot be less than " + AppAssistant.MinDate.ToString("dd-MM-yyyy"));

            string _EmpNo = Request.Form["EmpNo"].ToString();
            List<VHR_EmployeeProfile> _emp = DDService.GetEmployeeInfo(LoggedInUser).Where(aa => aa.OEmpID == _EmpNo).ToList();
            VHR_EmployeeProfile employee = DDService.GetEmployeeInfo(LoggedInUser).Where(aa => aa.OEmpID == _EmpNo).First();
            var RBValue = Request.Form["HalfLvHA"];

            if (_emp.First().LineManagerID == null)
                ModelState.AddModelError("EmpID", "There is no Line Manager associated with your profile. Please contact HR");
            {
                LeavePolicy lvPolicy = new LeavePolicy();
                LeaveType lvType = DDService.GetLeaveType().First(aa => aa.PLeaveTypeID == lvapplication.LeaveTypeID);
                if (_emp.Count == 0)
                {
                    ModelState.AddModelError("FromDate", "Emp No not exist");
                }
                else
                {
                    lvapplication.EmpID = _emp.FirstOrDefault().PEmployeeID;
                    lvPolicy = AssistantLeave.GetEmployeeLeavePolicyID(_emp, lvapplication.LeaveTypeID, DDService.GetLeavePolicy().ToList());

AppESSP/Areas/ESSP/Views/ESSPLeaveApp/Delete.cshtml
@model ESSPCORE.EF.LeaveApplication
<div class="modal-header bg-blue-800">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">
        <i class="glyphicon glyphicon-trash"></i> &nbsp;Delete Leave Application
    </h4>
</div>
<div class="modal-body">
    <div class="form-horizontal">
        <div>
            <h3 class="text-center"><strong> Are you sure you want to delete this Leave Application? </strong></h3>

            @using (Html.BeginForm(null, null, FormMethod.Get, new { name = "formDeleteID", id = "formDeleteID" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.PLeaveAppID)
            }
        </div>
    </div>
</div>
<div class="modal-footer">
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-custom-grey bg-grey" })
    <input type="button" id="btnPostDelete" class="btn btn-danger bg-danger-800" value="Delete" />
</div>
        <script type="text/javascript">
            $(document).ready(function () {
                EmpLvAppPostDelete();
            });
        </script>

AppESSP/Areas/ESSP/Views/ESSPLeaveApp/Index.cshtml
@model PagedList.IPagedList<ESSPCORE.EF.VAT_LeaveApplication>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ESSP Leave Application - List(ESSP)";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ESSPCORE.Common.VMLoggedUser LoggedInUser = (ESSPCORE.Common.VMLoggedUser)HttpContext.Current.Session["LoggedInUser"];

    <div class="page-header">
        <div class="page-header-content">
            <div class="col-md-6"><h4><i class="icon-arrow-right6 position-left text-black"></i> <span class="text-black">My Leave Application</span></h4></div>
            <div class="col-md-6" style="padding-top:8px;">
                <form class="form-inline" role="form">
                    <div class="form-group pull-right SearchBtnMargin">
                        @using (Html.BeginForm("Index", "ESSPLeaveApp", FormMethod.Get))
                        {<p>
                                Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                                <input class="btn btn-sm btn-custom bg-blue-800" type="submit" value="Search" />
                            </p>}
                    </div>
                </form>
            </div>

        </div>
    </div>

    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Basic datatable -->
                <div class="panel panel-flat">
                    <div class="breadcrumb-line bg-grey">
                        <a class="breadcrumb-elements-toggle"><i class="icon-menu-open"></i></a>
                        <ul class="breadcrumb">
                            <li><a href="~/Home/LoadDashboard"> Dashboard</a></li>
                            <li class="active"><a href="~/ESSP/ESSPLeaveApp">My Leave Applications</a></li>
                        </ul>
                        <ul class="breadcrumb-elements bg-blue-800" style="margin-right:-20px">
                            <li><a href="#" id="btnGetCreate"><i class="icon-add position-left"></i> Add Leave Applications</a></li>
                        </ul>
                    </div>
                    <table class="table table-bordered table-framed table-striped table-hover table-condensed">
                        <thead>
                            <tr>
                                <th class="text-bold">
                                    Leave ID
                                </th>
                                <th class="text-bold">
                                    Leave Date
                                </th>
                                <th class="text-bold">
                                    Emp Name
                                </th>
                                <th class="text-bold">
                                    Leave Type
                                </th>
                                <th class="text-bold">
                                    From Date
                                </th>
                                <th class="text-bold">
                                    To Date
                                </th>
                                <th class="text-bold">
                                    Return Date
                                </th>
                                <th class="text-bold">
                                    No Of Days
                                </th>
                                <th class="text-bold">
                                    Status
                                </th>
                                <th class="text-bold">
                                    View
                                </th>
                            </tr>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PLeaveAppID)
                                </td>
                                <td>
                                    @item.LeaveDate.ToString("dd-MMM-yyyy")
                                </td>
                                <td>
                                    @item.EmployeeName
                                </td>
                                <td>
                                    @if (item.IsAccum == true)
                                    {
                                        <span> Accumulated </span>
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => item.LeaveTypeName)
                                    }

                                </td>
                                <td>
                                    @item.FromDate.ToString("dd-MMM-yyyy")
                                </td>
                                <td>
                                    @item.ToDate.ToString("dd-MMM-yyyy")
                                </td>
                                <td>
                                    @if (item.ReturnDate != null)
                                    {@item.ReturnDate.Value.ToString("dd-MMM-yyyy")}
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NoOfDays)
                                </td>
                                <td>
                                    @if (item.LeaveStageID == "A")
                                    {
                                        <span class="label label-success">Approved</span>
                                    }
                                    @if (item.LeaveStageID == "P")
                                    {
                                        <span class="label label-info">Pending</span>
                                    }
                                    @if (item.LeaveStageID == "R")
                                    {
                                        <span class="label label-danger">Rejected</span>
                                    }
                                    @if (item.LeaveStageID == "D")
                                    {
                                        <span class="label label-danger">Recommended</span>
                                    }
                                    @if (item.LeaveStageID == "L")
                                    {
                                        <span class="label label-danger">Revert by LM</span>
                                    }
                                </td>

                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn border-blue-800 btn-flat text-indigo-600 btn-xs btn-icon btn-rounded dropdown-toggle" data-toggle="dropdown"><i class="icon-cog5"></i><span class="caret"></span></button>
                                        <ul class="dropdown-menu">

                                            <li>
                                                <a href="@Url.Action("Detail", "ESSPLeaveApp", new { id = item.PLeaveAppID })">Details</a>
                                            </li>
                                            @if (item.LeaveStageID == "P")
                                            {
                                                <li>
                                                    <a href="#" id="btnGetDelete" onclick="EmpLvAppGetDelete(@item.PLeaveAppID)" class="text-warning-800 note-icon-trash"> Delete</a>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /basic datatable -->
            </div>
            <!-- /main content -->
        </div>
        <!-- /page content -->
    </div>
    <!-- /page container -->
    <!-- Modal -->
    <div>
        <div class="modal fade" id="myModal"role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div id="modelBody">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript" src="~/Areas/ESSP/Scripts/EmpLeaveApplication.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        EmpLvAppGetCreate();
    });
</script>

AppESSP/Areas/ESSP/Views/ESSPLeaveApp/LeaveApplicationHistoryIndex.cshtml
@model PagedList.IPagedList<ESSPCORE.EF.VAT_LeaveApplication>
@using PagedList.Mvc;
@{
    ViewBag.Title = "ESSP Leave Application History - List(Bestway:ESSP)";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ESSPCORE.Common.VMLoggedUser LoggedInUser = (ESSPCORE.Common.VMLoggedUser)HttpContext.Current.Session["LoggedInUser"];

<div class="page-header">
    <div class="page-header-content">
        <div class="col-md-6"><h4><i class="icon-arrow-right6 position-left text-black"></i> <span class="text-black">Leave Application History</span></h4></div>
        <div class="col-md-6" style="padding-top:8px;">
            <form class="form-inline" role="form">
                <div class="form-group pull-right SearchBtnMargin">
                    @using (Html.BeginForm("LeaveApplicationHistoryIndex", "ESSPLeaveApp", FormMethod.Get))
                    {<p>
                            Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                            <input class="btn btn-sm btn-custom bg-blue-800" type="submit" value="Search" />
                        </p>}
                </div>
            </form>
        </div>

    </div>
</div>
    <!-- Page container -->
    <div class="page-container">
        <!-- Page content -->
        <div class="page-content">
            <!-- Main content -->
            <div class="content-wrapper">
                <!-- Basic datatable -->
                <div class="panel panel-flat">
                    <div class="breadcrumb-line bg-grey">
                        <a class="breadcrumb-elements-toggle"><i class="icon-menu-open"></i></a>
                        <ul class="breadcrumb">
                            <li><a href="~/Home/LoadDashboard"> Dashboard</a></li>
                            <li><a href="~/ESSP/ESSPLeaveApp/LeaveApplicationHistoryIndex"> Leave Applications history</a></li>
                        </ul>

                    </div>
                    <table class="table table-bordered table-framed table-striped table-hover table-condensed">
                        <thead>
                            <tr>

                                <th class="text-bold">
                                    Emp Name
                                </th>
                                <th class="text-bold">
                                    Leave Type
                                </th>
                                <th class="text-bold">
                                    From Date
                                </th>
                                <th class="text-bold">
                                    To Date
                                </th>
                                <th class="text-bold">
                                    Return Date
                                </th>
                                <th class="text-bold">
                                    No Of Days
                                </th>
                                <th class="text-bold">
                                    Status
                                </th>
                                <th class="text-bold">
                                    Action
                                </th>
                            </tr>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>

                                <td>
                                    @Html.DisplayFor(modelItem => item.EmployeeName)
                                </td>
                                <td>
                                    @if (item.IsAccum == true)
                                    {
                                        <span> Accumulated </span>
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => item.LeaveTypeName)
                                    }

                                </td>
                                <td>
                                    @item.FromDate.ToString("dd-MMM-yyyy")
                                </td>
                                <td>
                                    @item.ToDate.ToString("dd-MMM-yyyy")
                                </td>
                                <td>
                                    @item.ReturnDate.Value.ToString("dd-MMM-yyyy")
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NoOfDays)
                                </td>
                                <td>
                                    @if (item.LeaveStageID != null)
                                    {
                                        if (item.LeaveStageID == "A")
                                        {
                                            <span class="label label-success">Approved</span>
                                        }
                                        if (item.LeaveStageID == "P")
                                        {
                                            <span class="label label-info">Pending</span>
                                        }
                                        if (item.LeaveStageID == "R")
                                        {
                                            <span class="label label-danger">Rejected</span>
                                        }
                                        if (item.LeaveStageID == "D")
                                        {
                                            <span class="label label-success">Recomended</span>
                                        }
                                    }
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn border-blue-800 btn-flat text-indigo-600 btn-xs btn-icon btn-rounded dropdown-toggle" data-toggle="dropdown"><i class="icon-cog5"></i><span class="caret"></span></button>
                                        <ul class="dropdown-menu">

                                            <li>
                                                <a href="@Url.Action("Detail", "ESSPLeaveApp", new { id = item.PLeaveAppID })">Details</a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>

                </div>
                <!-- /basic datatable -->
            </div>
            <!-- /main content -->
        </div>
        <!-- /page content -->
    </div>
    <!-- /page container -->
    <!-- Modal -->
}