AppESSP/Areas/Attendance/Controllers/ServiceLogController.cs
using ESSPCORE.Common;
using ESSPCORE.EF;
using ESSPSERVICE.Generic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace AppESSP.Areas.Attendance.Controllers
{
    public class ServiceLogController : Controller
    {
        // GET: HumanRecource/Designation
        IEntityService<VAT_ServiceLog> ServiceLogService;
        IEntityService<DeviceData> DeviceDataService;
        IDDService DDService;
        public ServiceLogController(IEntityService<VAT_ServiceLog> serviceLogyService, IEntityService<DeviceData> deviceDataService,
             IDDService dDService)
        {
            ServiceLogService = serviceLogyService;
            DeviceDataService = deviceDataService;
            DDService = dDService;
        }
        public ActionResult Index(int? ErrorCode, int? ReaderID, DateTime? DateStart, DateTime? DateEnd)
        {
            if (ErrorCode == null)
                ErrorCode = 0;
            if (ReaderID == null)
                ReaderID = 0;
            if (DateStart == null)
                DateStart = DateTime.Today.AddDays(-1);
            if (DateEnd == null)
                DateEnd = DateTime.Now;
            else
                DateEnd = DateEnd + new TimeSpan(23,59,59);
            ViewBag.ErrorCode = new SelectList(
                                new List<SelectListItem>
                                {
                                     new SelectListItem { Text = "All", Value = "0"},
                                    new SelectListItem { Text = "Failed", Value = "1"},
                                    new SelectListItem { Text = "Success", Value = "5"},
                                }, "Value", "Text");
            List<Reader> readers = DDService.GetReader().ToList().OrderBy(aa => aa.ReaderName).ToList();
            readers.Insert(0, new Reader { PReaderID = 0, ReaderName = "All" });
            ViewBag.ReaderID = new SelectList(readers, "PReaderID", "ReaderName", ReaderID);
            Expression<Func<VAT_ServiceLog, bool>> SpecificEntries = c => c.DateTime >=DateStart && c.DateTime<=DateEnd;
            List<VAT_ServiceLog> list = ServiceLogService.GetIndexSpecific(SpecificEntries);
            if (ReaderID > 0)
                list = list.Where(aa => aa.PReaderID == ReaderID).ToList();
            if (ErrorCode > 0)
                list = list.Where(aa => aa.ErrorCode == ErrorCode).ToList();
            ViewBag.DateStart = DateStart.Value.ToString("yyyy-MM-dd");
            ViewBag.DateEnd = DateEnd.Value.ToString("yyyy-MM-dd");
            if (DateStart > DateEnd)
            {
                ViewBag.Message = "Start date must be less than end date!";
            }
            return View(list.OrderByDescending(aa=>aa.DateTime).ToList());
        }
        #region -- Private Method--
        
        #endregion
    }
}

AppESSP/Areas/Attendance/Views/ServiceLog/Index.cshtml
@model List<ESSPCORE.EF.VAT_ServiceLog>
@{
    ViewBag.Title = "Service Log - List (Bestway:ESSP)";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header ">

    <div class="page-header-content">
        <h4><i class="icon-arrow-right6 position-left text-black"></i> <span class="text-black">Service Log</span></h4>
    </div>
</div>
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="breadcrumb-line bg-grey">
                    <a class="breadcrumb-elements-toggle"><i class="icon-menu-open"></i></a>
                    <ul class="breadcrumb">
                        <li><a href="index.html"> Dashboard</a></li>
                        <li class="active"> Service Log</li>
                    </ul>
                </div>
                @using (Html.BeginForm("Index", "ServiceLog", FormMethod.Post, new { name = "formCreateID", id = "formCreateID" }))
                {
                    <div class="form-group ">
                        <div class="col-md-12">
                            <div class="col-md-1">
                                @Html.DropDownList("ErrorCode", null, new { @class = "btn btn-default col-lg-12 col-sm-12 col-md-12" })
                            </div>
                            <div class="col-md-3">
                                @Html.DropDownList("ReaderID", null, new { @class = "btn btn-default col-lg-12 col-sm-12 col-md-12" })
                            </div>
                            <div class="col-md-1">
                                <label class="control-label pull-right">Start: </label>
                            </div>
                            <div class="col-md-2">
                                <input type="date" class="form-control " name="DateStart" id="DateStart" value="@ViewBag.DateStart" />
                            </div>
                            <div class="col-md-1">
                                <label class="control-label pull-right">End: </label>
                            </div>
                            <div class="col-md-2">

                                <input type="date" class="form-control " name="DateEnd" id="DateEnd" value="@ViewBag.DateEnd" />
                            </div>

                            <div class="col-md-1">
                                <input type="submit" class="btn bg-blue-800" value="GO" />
                            </div>
                        </div>
                    </div>
                }
                <table class="table datatable-basic ">
                    <thead>
                        <tr>

                            <th class="text-bold">
                                Description
                            </th>
                            <th class="text-bold">
                                DateTime
                            </th>
                            <th class="text-bold">
                                Reader Name
                            </th>
                            <th class="text-bold">
                                Location Name
                            </th>
                            @*<th class="text-bold">
                                Attendance Processed
                                 </th>*@

                        </tr>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @item.DateTime.ToString("dd-MMM-yyyy hh:mm tt")
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReaderName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LocationName)
                                </td>
                                @*<td>
                                        @if (item.Processed == true)
                                        {
                                            <span>Processed </span>
                                        }
                                        else if (item.Processed == false)
                                        {
                                            <span>In Process</span>
                                        }
                                        else if (item.Processed == null)
                                        {
                                            <span>In Process</span>
                                        }
                                    </td>*@

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /basic datatable -->
        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>