AppESSP/Areas/Attendance/Controllers/DailyOvertimeController.cs
using AppESSP.Controllers;
using ESSPCORE.Common;
using ESSPCORE.EF;
using ESSPSERVICE.Attendance;
using ESSPSERVICE.Generic;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace AppESSP.Areas.Attendance.Controllers
{
    public class DailyOvertimeController : BaseController
    {
        // GET: Attendance/DailyOvertimeEditor
        IEntityService<DailyOvertime> DailyOvertimeService;
        IEntityService<DailyAttendance> DailyAttendanceService;
        IEntityService<VAT_DailyOvertime> VATDailyOvertimeService;
        IEntityService<Employee> EmployeeService;
        IEntityService<VHR_EmployeeProfile> vHR_EmployeeProfile;
        IEntityService<PayrollPeriod> PayrollPeriodService;
        IEntityService<LeaveCPLPool> LeaveCPLPoolService;
        IEntityService<LeaveCPLEmpBalance> LeaveCPLEmpBalanceService;
        IEntityService<LeaveQuotaYear> LeaveQuotaYearService;
        IGetSpecificEmployeeService GetSpecificEmployeeService;
        IDDService DDService;
        public DailyOvertimeController(IEntityService<DailyOvertime> dailyOvertimeService, IEntityService<VAT_DailyOvertime> vATDailyOvertimeService
            , IDDService dDService, IEntityService<Employee> employeeService, IEntityService<DailyAttendance> dailyAttendanceService, IGetSpecificEmployeeService getSpecificEmployeeService,
            IEntityService<LeaveCPLPool> dbLeavePoolCPL, IEntityService<LeaveCPLEmpBalance> dbLeaveBalanceCPL, IEntityService<LeaveQuotaYear> leaveQuotaYearService
            , IEntityService<PayrollPeriod> payrollPeriodService, IEntityService<VHR_EmployeeProfile> vHREmployeeProfile)
        {
            VATDailyOvertimeService = vATDailyOvertimeService;
            DailyOvertimeService = dailyOvertimeService;
            EmployeeService = employeeService;
            DDService = dDService;
            DailyAttendanceService = dailyAttendanceService;
            GetSpecificEmployeeService = getSpecificEmployeeService;
            LeaveCPLPoolService = dbLeavePoolCPL;
            LeaveCPLEmpBalanceService = dbLeaveBalanceCPL;
            LeaveQuotaYearService = leaveQuotaYearService;
            PayrollPeriodService = payrollPeriodService;
            vHR_EmployeeProfile = vHREmployeeProfile;
        }
        public ActionResult Index(string searchString, string currentFilter, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            VMLoggedUser LoggedInUser = Session["LoggedInUser"] as VMLoggedUser;
            List<VAT_DailyOvertime> list = GetSpecificEmployeeService.GetSpecificDailyOT(LoggedInUser).OrderByDescending(a => a.OTDate).ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(aa => aa.OEmpID.Contains(searchString) || aa.EmployeeName.ToUpper().Contains(searchString.ToUpper()) || aa.PDailyOTID.ToString().Contains(searchString)).ToList();

            }
            int pageSize = 15;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Create()
        {
            DailyOvertime obj = new DailyOvertime();
            return View(obj);
        }
        [HttpPost]
        public ActionResult Create(DailyOvertime obj)
        {
            string _EmpNo = Request.Form["EmpNo"].ToString();
            Expression<Func<VHR_EmployeeProfile, bool>> SpecificEntries121 = c => c.OEmpID == _EmpNo;
            VMLoggedUser LoggedInUser = Session["LoggedInUser"] as VMLoggedUser;
            List<VHR_EmployeeProfile> _emp = vHR_EmployeeProfile.GetIndexSpecific(SpecificEntries121);
            if (obj.OTDate == null || obj.OTDate <= DateTime.Today.AddDays(-200))
                ModelState.AddModelError("OTDate", "OT Date must be valid");
            else
            {
                if (!DDService.IsDateLieBetweenActivePayroll(obj.OTDate.Value))
                    ModelState.AddModelError("OTDate", "Payroll Period is Closed for this date");
            }
            if ((obj.SingleEncashableOT == null && obj.SingleEncashableOT <= 0) && (obj.DoubleEncashbaleOT == null && obj.DoubleEncashbaleOT <= 0) && (obj.CPLOT == null && obj.CPLOT <= 0))
                ModelState.AddModelError("SingleEncashableOT", "Overtime must be valid");
            if (_emp.Count == 0)
            {
                ModelState.AddModelError("OTDate", "Emp No not exist");
            }
            else
            {
                // int? EmpLocID = _emp.First().LocationID;
                //if (LoggedInUser.UserLoctions.Where(aa => aa.LocationID == EmpLocID).Count() == 0)
                //ModelState.AddModelError("OTDate", "You do not have rights to add overtime for this employee");
                int? EmpDepID = _emp.First().OUCommonID;
                if (LoggedInUser.UserDepartments.Where(aa => aa.DepartmentID == EmpDepID).Count() == 0)
                    ModelState.AddModelError("OTDate", "You do not have rights to add overtime for this employee");
                obj.EmployeeID = _emp.First().PEmployeeID;
                Expression<Func<DailyOvertime, bool>> SpecificEntries2 = c => c.EmployeeID == obj.EmployeeID && c.OTDate == obj.OTDate;
                if (DailyOvertimeService.GetIndexSpecific(SpecificEntries2).Count > 0)
                    ModelState.AddModelError("OTDate", "Already have OT for this date");
            }

            if (ModelState.IsValid)
            {
                if (obj.SingleEncashableOT > 0)
                {
                    obj.SingleEncashableOT = obj.SingleEncashableOT * 60;
                }
                if (obj.DoubleEncashbaleOT > 0)
                {
                    obj.DoubleEncashbaleOT = obj.DoubleEncashbaleOT * 60;
                }
                if (obj.CPLOT > 0)
                {
                    obj.CPLOT = obj.CPLOT * 60;
                }
                obj.AddedByUserID = LoggedInUser.PUserID;
                obj.AddedDate = DateTime.Now;
                DailyOvertimeService.PostCreate(obj);
                // Update Attendance Data
                Expression<Func<DailyAttendance, bool>> SpecificEntries2 = c => c.EmpID == obj.EmployeeID && c.AttDate == obj.OTDate;
                List<DailyAttendance> attDatas = DailyAttendanceService.GetIndexSpecific(SpecificEntries2).ToList();
                if (attDatas.Count > 0)
                {
                    DailyAttendance attdata = attDatas.First();
                    if (obj.SingleEncashableOT > 0)
                    {
                        attdata.ApprovedOT = (short)obj.SingleEncashableOT;

                    }
                    if (obj.DoubleEncashbaleOT > 0)
                    {
                        attdata.ApprovedDoubleOT = (short)obj.DoubleEncashbaleOT;

                    }
                    if (obj.CPLOT > 0)
                    {
                        attdata.ApprovedCPL = (short)obj.CPLOT;
                    }
                    DailyAttendanceService.PostEdit(attdata);
                    DDService.ProcessMonthlyAttendance((DateTime)obj.OTDate, (int)obj.EmployeeID, obj.EmployeeID.ToString());
                    // Update Employee Pool
                    LeaveCPLPool dbLeavePoolCPL = new LeaveCPLPool();
                    Expression<Func<LeaveCPLPool, bool>> SpecificEntries3 = c => c.EmployeeID == obj.EmployeeID;

                    if (LeaveCPLPoolService.GetIndexSpecific(SpecificEntries3).Count() > 0)
                    {

                        dbLeavePoolCPL = LeaveCPLPoolService.GetIndexSpecific(SpecificEntries3).First();
                        dbLeavePoolCPL.LastEntryDateTime = DateTime.Now;
                        dbLeavePoolCPL.RemainingHours = dbLeavePoolCPL.RemainingHours + (obj.CPLOT / 60);
                        if (dbLeavePoolCPL.RemainingHours == null)
                        {
                            dbLeavePoolCPL.RemainingHours = 0;
                            dbLeavePoolCPL.RemainingHours = (dbLeavePoolCPL.RemainingHours) + (obj.CPLOT / 60);
                        }                      
                        dbLeavePoolCPL.TotalHours =(dbLeavePoolCPL.TotalHours) + (obj.CPLOT / 60);
                        if (dbLeavePoolCPL.TotalHours == null)
                        {
                            dbLeavePoolCPL.TotalHours = 0;
                            dbLeavePoolCPL.TotalHours =( dbLeavePoolCPL.TotalHours) + (obj.CPLOT / 60);
                        }
                        dbLeavePoolCPL.CPLDays = 0;
                        LeaveCPLPoolService.PostEdit(dbLeavePoolCPL);
                    }
                    else
                    {
                        dbLeavePoolCPL = new LeaveCPLPool();
                        dbLeavePoolCPL.EmployeeID = obj.EmployeeID;
                        dbLeavePoolCPL.LastEntryDateTime = DateTime.Now;
                        dbLeavePoolCPL.RemainingHours = obj.CPLOT / 60;
                        dbLeavePoolCPL.TotalHours = obj.CPLOT / 60;
                        dbLeavePoolCPL.CPLDays = 0;
                        LeaveCPLPoolService.PostCreate(dbLeavePoolCPL);
                    }
                    // Update CPL
                    if (dbLeavePoolCPL.RemainingHours >= 4)
                    {

                        int total = (int)(dbLeavePoolCPL.RemainingHours / 4);
                        float remaining = (float)(dbLeavePoolCPL.RemainingHours - (total * 4));
                        float days = (float)(total / 2.0);
                        // Add into CPL Balance
                        LeaveCPLEmpBalance dbLeaveBalanceCPL = new LeaveCPLEmpBalance();
                        dbLeaveBalanceCPL.EmployeeID = obj.EmployeeID;

AppESSP/Areas/Attendance/Views/DailyOvertime/Create.cshtml
@model ESSPCORE.EF.DailyOvertime

@using (Html.BeginForm(null, null, FormMethod.Get, new { name = "formCreateID", id = "formCreateID" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header bg-blue">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">
            <i class="icon-menu7"></i> &nbsp;Daily Overtime
        </h4>
    </div>

    <div class="modal-body">
        <div class="form-horizontal">
            <section class="col-md-8">
                <div class="form-group">
                    <div class="control-label text-semibold col-md-12  ">In case of Rest or Gazetted holidays system will consider actual overtime. If you want to add One CPL against 4 Hours then you should enter 8 Hours in CPL Hours</div>
                </div>
                <div class="form-group">
                    <div class="form-inline">
                        <label class="col-lg-2 col-md-2 col-sm-2 control-label text-semibold">Emp No<span style="color:red;">*</span></label>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="input-group">
                                <input id="EmpNo" name="EmpNo" autofocus type="text" class="form-control" placeholder="EMP-00001" focus />
                                <span class="input-group-btn">
                                    <button type="button" name="btnGetEmployee" value="Search" class="btn btn-primary bg-success" id="btnGetEmployee" style="padding-bottom:.6em">Search</button>
                                </span>
                            </div>
                        </div>
                        <div class="control-label text-semibold col-md-2 text-right "> Date<span style="color:red;">*</span></div>
                        <div class="col-md-4">
                            @Html.TextBoxFor(x => x.OTDate, new { @class = "form-control required", @type = "date" })
                            @Html.ValidationMessageFor(model => model.OTDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="control-label text-semibold col-md-3 ">Single OT (hours)</div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.SingleEncashableOT, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SingleEncashableOT, "", new { @class = "text-danger" })
                    </div>
                    <div class="control-label text-semibold col-md-3  ">Double OT(hours)</div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.DoubleEncashbaleOT, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DoubleEncashbaleOT, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label text-semibold col-md-3  ">CPL OT (hours)</div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.CPLOT, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CPLOT, "", new { @class = "text-danger" })
                    </div>
                </div>

            </section>
            <section class="col-md-4">
                <div class="content-group">
                    <div class="panel-body bg-blue border-radius-top text-center" style="height:50px">
                        <h6 class="text-bold" style="margin-top:-5px">
                            EMPLOYEE INFORMATION
                        </h6>
                    </div>
                    <div class="panel panel-flat">
                        <div class="table-responsive">
                            <table class="table table-condensed">

                                <tbody>
                                    <tr>
                                        <td class="small text-bold">
                                            Name:
                                        </td>
                                        <td>
                                            <h6 id="EName" class="small"></h6>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="small text-bold">
                                            Position:
                                        </td>

                                        <td>
                                            <h6 id="EDesignation" class="small"></h6>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td class="small text-bold">
                                            OU:
                                        </td>

                                        <td>
                                            <h6 id="EOU" class="small"></h6>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="small text-bold">
                                            DOJ:
                                        </td>
                                        <td>
                                            <h6 id="EDOJ" class="small"></h6>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>

        </div>

    </div>
    <div class="modal-footer">
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary bg-primary-300", tabindex = 1 })
        <button type="button" id="btnPostCreate" class="btn btn-success bg-success-800" value="Submit">Submit</button>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        DailyOvertimePostCreate();
        EmployeeInfo();
    });
</script>

AppESSP/Areas/Attendance/Views/DailyOvertime/Delete.cshtml
@model ESSPCORE.EF.DailyOvertime
<div class="modal-header bg-blue">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">
        <i class="icon-menu7"></i> &nbsp;Delete Daily Overtime
    </h4>
</div>
@using (Html.BeginForm(null, null, FormMethod.Get, new { name = "formDeleteID", id = "formDeleteID" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.PDailyOTID)
    @Html.HiddenFor(model => model.AddedDate)
    @Html.HiddenFor(model => model.SingleEncashableOT)
    @Html.HiddenFor(model => model.DoubleEncashbaleOT)
    @Html.HiddenFor(model => model.OTDate)
    @Html.HiddenFor(model => model.EmployeeID)
    @Html.HiddenFor(model => model.CPLOT)
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="form-group">
                <h3 class="text-center"> Are you sure you want to delete this Leave Application?</h3>
                <div class="text-center">
                    <h5>
                        @Html.ValidationMessageFor(model => model.OTDate, "", new { @class = "text-danger" })
                    </h5>
                </div>
            </div>
        </div>
    </div>
}
<div class="modal-footer">
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary bg-primary-300" })
    <input type="button" id="btnPostDelete" class="btn btn-danger bg-danger-800" value="Delete" />

</div>
<script type="text/javascript">
    $(document).ready(function () {
        DailyOvertimePostDelete();
    });
</script>

AppESSP/Areas/Attendance/Views/DailyOvertime/Index.cshtml
@model PagedList.IPagedList<ESSPCORE.EF.VAT_DailyOvertime>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Daily Overtime - List (Bestway:ESSP)";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ESSPCORE.Common.VMLoggedUser LoggedInUser = (ESSPCORE.Common.VMLoggedUser)HttpContext.Current.Session["LoggedInUser"]; }
<div class="page-header">
    <div class="page-header-content">
        <div class="col-md-6"><h4><i class="icon-arrow-right6 position-left text-black"></i> <span class="text-black">Daily Overtime Editor</span></h4></div>
        <div class="col-md-6" style="padding-top:8px;">
            <form class="form-inline" role="form">
                <div class="form-group pull-right SearchBtnMargin">
                    @using (Html.BeginForm("Index", "DailyOvertime", FormMethod.Get))
                    {<p>
                            Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                            <input class="btn btn-sm bg-green-600" type="submit" value="Search" />
                        </p>}
                </div>
            </form>
        </div>

    </div>
</div>
<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">
            <!-- Basic datatable -->
            <div class="panel panel-flat">
                <div class="breadcrumb-line bg-green-600">
                    <a class="breadcrumb-elements-toggle"><i class="icon-menu-open"></i></a>
                    <ul class="breadcrumb">
                        <li><a href="index.html"> Dashboard</a></li>
                        <li class="active"> Daily Overtime Editor</li>
                    </ul>
                    <ul class="breadcrumb-elements bg-green-800" style="margin-right:-20px">
                        <li><a href="#" id="btnGetCreate"><i class="icon-add position-left"></i>Add Overtime</a></li>
                    </ul>
                </div>
                <table class="table table-bordered table-framed table-striped table-hover table-condensed">
                    <thead>
                        <tr>
                            <th class="text-bold">
                                Emp No
                            </th>
                            <th class="text-bold text-size-mini">
                                Employee Name
                            </th>
                            <th class="text-bold">
                                Attendance Date
                            </th>
                            <th class="text-bold">
                                Single OT
                            </th>
                            <th class="text-bold">
                                Double OT
                            </th>
                            <th class="text-bold">
                                CPL OT
                            </th>

                            @*@if (LoggedInUser.TMSDelete == true && item.CPLOT == null)
                            {
                                <th class="text-bold">
                                    Delete
                                </th>
                            }*@
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.OEmpID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EmployeeName)
                                </td>
                                <td>
                                    @item.OTDate.Value.ToString("dd-MMM-yyyy")
                                </td>
                                <td>
                                    @if (item.SingleEncashableOT > 0)
                                    {
                                        TimeSpan span = TimeSpan.FromMinutes(item.SingleEncashableOT.Value);
                                        int hours = span.Hours;
                                        int mins = item.SingleEncashableOT.Value - hours * 60;
                                        <span>@hours.ToString("00"):@mins.ToString("00")</span>
                                    }
                                    else
                                    {
                                        @(item.SingleEncashableOT)
                                    }
                                </td>
                                <td>
                                    @if (item.DoubleEncashbaleOT > 0)
                                    {

                                        TimeSpan span = TimeSpan.FromMinutes(item.DoubleEncashbaleOT.Value);
                                        int hours = span.Hours;
                                        int mins = item.DoubleEncashbaleOT.Value - hours * 60;
                                        <span>@hours.ToString("00"):@mins.ToString("00")</span>

                                    }
                                    else
                                    {
                                        @(item.DoubleEncashbaleOT)
                                    }
                                </td>
                                <td>
                                    @if (item.CPLOT > 0)
                                    {

                                        TimeSpan span = TimeSpan.FromMinutes(item.CPLOT.Value);
                                        int hours = span.Hours;
                                        int mins = item.CPLOT.Value - hours * 60;
                                        <span>@hours.ToString("00"):@mins.ToString("00")</span>
                                    }
                                    else
                                    {
                                        @(item.CPLOT)
                                    }
                                </td>

                                @if (LoggedInUser.TMSDelete == true && item.CPLOT == null)
                                {
                                    <td>
                                        <button type="button" id="btnGetDelete" onclick="DailyOvertimeGetDelete(@item.PDailyOTID)" class="btn border-warning btn-xs text-warning-700 btn-flat btn-rounded"><i class="note-icon-trash"></i></button>
                                    </td>
                                }
                                else if (LoggedInUser.TMSDelete == true && item.CPLOT != null)
                                {
                                 
                                }
                            </tr>
                        }

                    </tbody>
                </table>
                <br />
                <div class="row">
                    <div class="col-md-10 pull-left">@Html.PagedListPager(Model, page => Url.Action("Index", new { Status = ViewBag.StatusSave, Location = ViewBag.LocIDSave, page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))</div>
                    <div class="col-md-2 pull-right ">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>
                </div>
            </div>
            <!-- /basic datatable -->
        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->
<div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">

            <div class="modal-content ">
                <div id="modelBody">

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/Areas/Attendance/Scripts/DailyOvertime.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        DailyOvertimeGetCreate();
    });
</script>